version: 1.0.{build}
image: Visual Studio 2013
platform: x64
configuration: Release

build:
  parallel: true
  project: VS2013/RenderGirlOpenCL.sln
  verbosity: normal

install:
  - git submodule update --init --recursive
